FROM n8nio/n8n:latest
USER root
RUN apk add --no-cache su-exec
COPY n8n-railway-entrypoint.sh /docker-entrypoint-railway.sh
RUN chmod +x /docker-entrypoint-railway.sh
ENTRYPOINT ["/docker-entrypoint-railway.sh"]
